/* telemok.com/patterns/pattern4503599627370707/ */
export var telemokPatternsData = new Map([
	[4503599627370707,{json:`{
    "patternType": "struct",
    "patternVersion": 1,
    "patternBits": 576,
    "patternName": "Karat307Testx",
    "patternDescription": "\\u041f\\u0440\\u043e\\u0431\\u043d\\u044b\\u0439 \\u0448\\u0430\\u0431\\u043b\\u043e\\u043d, \\u0447\\u0442\\u043e\\u0431\\u044b \\u043e\\u0446\\u0435\\u043d\\u0438\\u0442\\u044c \\u0432\\u043e\\u0437\\u043c\\u043e\\u0436\\u043d\\u043e\\u0441\\u0442\\u044c \\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u0438\\u044f \\u0434\\u0430\\u043d\\u043d\\u044b\\u0445 \\u0441 \\u041a\\u0410\\u0420\\u0410\\u0422-307",
    "structItems": [
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "termo0raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "",
            "structItemDefault": "0",
            "structItemMerge": "random",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "termo1raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "",
            "structItemDefault": "0",
            "structItemMerge": "random",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "termo2raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "",
            "structItemDefault": "0",
            "structItemMerge": "random",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "termo3raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "",
            "structItemDefault": "0",
            "structItemMerge": "random",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "termo4raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "termo5raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "flow0raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "flow1raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "flow2raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "flow3raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "flow4raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "flow5raw",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "pressure0",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "pressure1",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "pressure2",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "pressure3",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "pressure4",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        },
        {
            "structItemPatternBits": 32,
            "structItemPatternId": 0,
            "structItemCount": 1,
            "structItemVarName": "pressure5",
            "structItemPatternType": "native",
            "structItemPatternName": "Unsigned",
            "structItemDescription": "Unsigned native value",
            "structItemDefault": "0",
            "structItemMerge": "average",
            "structItemArrayType": "NONE"
        }
    ]
}`}]]);